name: example
description: "Data Monitor Code Generation Example."
version: 1.0.3

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  data_monitor: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  data_monitor_generators: ^1.0.0
  flutter_lints: ^6.0.0
