include: package:flutter_lints/flutter.yaml

dcm:
  extends:
    - recommended

  rules:
    avoid-dynamic: false
    prefer-prefixed-global-constants: false
    prefer-shorthands-with-static-fields: false
    prefer-shorthands-with-enums: false
